- name: Delete a resource group including resources it contains
  hosts: localhost
  vars:
    resource_group: #{resourceGroupName}#

  tasks:
  - name: Delete a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      state: absent