- name: Installing packages 
  connection: local
  hosts: [webserver]
  become: yes
  become_method: sudo
  remote_user: alezanper

  tasks: 
    - name: 1. install Apache
      apt: python-apt, apache2, php7.2, libapache2-mod-php7.2, python-mysqldb, php-mysql    
    - debug: msg="installed"