- name: Installing packages 
  hosts: [webserver]
  connection: local
  remote_user: alezanper
  become: yes
  become_method: sudo


  tasks: 
    - name: install lamp stack
      apt:
        name: apache2, php7.2, libapache2-mod-php7.2, python-mysqldb, php-mysql
        state: latest

    - name: start apache service
      service:
        name: apache2
        state: started
        enabled: yes