- name: Installing packages 
  hosts: [webserver]
  remote_user: alezanper
  become: yes
  become_method: sudo
  
  tasks: 

  # do an "apt-get update", to ensure latest package lists
  - name: Ensure python-apt is installed
    shell: 
      apt-get install python-apt -y -q
      creates=/usr/share/doc/python-apt
    warm: false

  - name: apt-get update
    apt:
      update_cache: yes
      upgrade: safe
    warm: false


  - name: install lamp stack
    apt:
      name: apache2, php7.2, libapache2-mod-php7.2, php-mysql
      state: latest
    warm: false

  - name: start apache service
    service:
      name: apache2
      state: started
      enabled: yes