- name: Installing packages 
  hosts: [webserver]
  remote_user: alezanper
  become: yes
  become_method: sudo
  
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-apt)"
    register: output
    changed_when: output.stdout != ""

  tasks: 
  - name: install lamp stack
    apt:
      name: apache2, php7.2, libapache2-mod-php7.2, php-mysql
      state: latest

  - name: start apache service
    service:
      name: apache2
      state: started
      enabled: yes