- name: Installing packages 
  hosts: [webserver]
  remote_user: alezanper
  become: yes
  become_method: sudo
  
  tasks: 

  # do an "apt-get update", to ensure latest package lists
  - name: apt-get update
    apt:
      update-cache: yes
      changed_when: 0

  # Upgrade all the Ubuntu servers.
 # do the actual apt-get dist-upgrade
  - name: apt-get dist-upgrade
    apt: upgrade=dist # upgrade all packages to latest version

  - name: install lamp stack
    apt:
      name: python-apt, apache2, php7.2, libapache2-mod-php7.2, python-mysqldb, php-mysql
      state: latest

  - name: start apache service
    service:
      name: apache2
      state: started
      enabled: yes