- name: Installing packages 
  hosts: [webserver]
  remote_user: alezanper
  become: yes
  become_method: sudo

  tasks: 

  - name: This command will change the working directory to somedir/.
    shell:
      cmd: apt-get install python-apt
    args:
      warn: false

  - name: install lamp stack
    apt:
      name: apache2, php7.2, libapache2-mod-php7.2, php-mysql
      state: latest

  - name: start apache service
    service:
      name: apache2
      state: started
      enabled: yes