- name: Installing packages 
  hosts: [webserver]

  tasks: 
    - name: install lamp stack
      become: yes
      become_user: root
      apt:
        pkg:
          - apache2
          - php7.3
          - php7.3-mysql
        state: present
        update_cache: yes

    - name: start apache service
      become: yes
      become_user: root
      service:
        name: apache2
        state: started
        enabled: yes