- name: Installing packages 
  hosts: [webserver]
  remote_user: alezanper
  become: yes
  become_method: sudo
  
  tasks: 

  # do an "apt-get update", to ensure latest package lists
  - name: apt-get update
    apt:
      update_cache: yes

  - name: install lamp stack
    apt:
      name: python-apt, apache2, php7.2, libapache2-mod-php7.2, python-mysqldb, php-mysql
      state: latest

  - name: start apache service
    service:
      name: apache2
      state: started
      enabled: yes